defaults:
  - hydra: default
  - _self_

hydra:
  searchpath:
    - file://conf/


data_dir: ../research.data/mm-safety/
train_file:
dev_file:
test_file: ${data_dir}/MM-SafetyBench/data/processed_questions

port: 6000
model: ds-coder-v1.5-chat

sampling_params:
  _target_: vllm.SamplingParams
  n: 1
  temperature: 0.0
  stop: [ "</s>", "\n\n\n\n", "Context:\n", "Thought 42:", "<|end_of_text|>", "<|eot_id|>", "<|EOT|>" ]
  max_tokens: 512

tem: ${sampling_params.temperature}
n: ${sampling_params.n}
split_size: -1
split_id: 0
max_num_seqs: 128
suffix: n${n}.tem${tem}

output_file: outputs/mm-safety/mm-safety-bench/mm-safety-bench.rephrase-q.img-desc-sd-typo.eval.${suffix}.json
flush_file: ${output_file}l

apply_chat_template: False
add_generation_prompt: True

gpu_memory_utilization: 0.8
prompt: "{Rephrased Question}"
chat_prefix: "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nYou are a helpful assistant to answer the questions from the user.<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nHere is a description of an image:\n\n{description}\n\n"
chat_suffix: "<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"

# Data loading
read_tensor:
  _target_: dataset.combine_dataset.ResponseAlignDataset
  read_fn:
    _target_: dataset.readers.json2list_reader
  aligner:
    _target_: dataset.input_aligner.field_extract_aligner
    input_index_field: id
    extract_index_field: id
    extract_fields: [ response ]
    extra_file: outputs/mm-safety/mm-safety-bench/mm-safety-bench.n1.tem0.0.img-desc-sd-typo.json
    renamed_fields:
      response: description
  template: ${chat_prefix}${prompt}${chat_suffix}
  instruction:
  index_field: "id"
  service_based: False
  split_size: ${split_size}
  split_id: ${split_id}
  max_data_num: -1

save_best: True
eval_sub_path:
output_dir: ../pretrained-models/Meta-Llama-3-8B-Instruct
#output_dir: ../pretrained-models/llama3-llava-next-8b-hf/

# Dataloader
num_workers: 32
prefetch_factor: 2

dp_size:
tp_size: 1
pp_size: 1

post_process:
  _target_: post_processors.api_callback.SafetyResponseCallback
  answer_clean:
  evaluator:
    _target_: post_processors.eval.keywords.KeyWordsEvaluator
  output_file: ${output_file}
  index_field: id
  saved_keys: [ "Question", "GPT-Pred", "Changed Question", "Key Phrase", "Phrase Type", "Rephrased Question", "Rephrased Question(SD)" ]

# Training hyper-parameters
per_gpu_train_batch_size: 1
per_gpu_eval_batch_size: 1

ddp_eval: False
no_cuda: False
seed: 42
local_rank: -1

# Temporary variables
fp16: True
fp16_bfloat16: True
n_gpu: 1
device:
train_batch_size:
eval_batch_size:
world_size: